name: recognise_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # python
  - python>=3.8
  - multiprocess
  # alignment
  - biopython
  - lastz
  - multiz
  - minigraph
  - gfatools
  # recombination
  - gubbins>=3.2.1
  # testing
  - pytest
  - pytest-cov
